language: php

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

php:
  - 7.2
  - 7.4
  - 'nightly'

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.4
      env: PHPCS=1 DEFAULT=0
    - php: 7.2
      env: STATIC_ANALYSIS=1 DEFAULT=0

cache:
  directories:
    - $HOME/.composer/cache

install:
  - |
      if [[ $TRAVIS_PHP_VERSION == 'nightly' ]]; then
        composer update --no-interaction --ignore-platform-reqs
      else
        composer update --no-interaction
      fi
  - if [[ $STATIC_ANALYSIS == 1 ]]; then composer require --dev psalm/phar:^3.13; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi
  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs -p --standard=PSR12 ./src ./tests; fi
  - if [[ $STATIC_ANALYSIS == 1 ]]; then vendor/bin/psalm.phar; fi

after_success:
  - |
      if [[ $DEFAULT == 1 ]]; then
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover
      fi
